/tracking/verbose 2

# Change the default number of workers (in multi-threading mode) 
#
/run/numberOfThreads 4

# Geometry Setups
/HUS/Geometry/Target/SetTargetXYDim    1. cm
/HUS/Geometry/Target/SetTargetZThick   324.786 nm
/HUS/Geometry/Target/SetTargetAngle    0. deg
/HUS/Geometry/Target/SetBaseXYDim      1. cm
/HUS/Geometry/Target/SetBaseZThick     36.70 nm
/HUS/Geometry/Detector/SetDet0Angle    40. deg
/HUS/Geometry/Detector/SetDet1Angle    70. deg
/HUS/Geometry/Detector/SetDet2Angle    150. deg
/HUS/Geometry/Detector/SetDet3Angle    233. deg
/HUS/Geometry/Detector/SetDet4Angle    270 deg
/HUS/Geometry/Detector/SetDet5Angle    330. deg

# Initialize kernel
#
/run/geometryModified
/run/initialize

# Setups proton beam
#
/HUS/Beam/SetBeamEnergy         2.0 MeV
/HUS/Beam/SetBeamRadius         0.01 mm
/HUS/Beam/SetBeamXPos           0. mm
/HUS/Beam/SetBeamYPos           0. mm
/HUS/Beam/SetBeamZPos           -1. cm
/HUS/Beam/SetMinSolidAngle      0. deg
/HUS/Beam/SetMaxSolidAngle      0.01 deg
/HUS/Beam/SetThetaRotationAngle 0. deg
/HUS/Beam/SetPhiRotationAngle   90. deg

#
# Visualization setting
/control/execute vis.mac
